language: php
php:
  - 5.3.3
  - 5.4
branches:
  only:
    - 7.x
env:
  - FEDORA_VERSION="3.5"
  - FEDORA_VERSION="3.6.2"
  - FEDORA_VERSION="3.7.0"
before_install:
  - cd $HOME
  - sudo apt-get -y install libxss1 xdg-utils libappindicator1
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod 755 chromedriver
  - sudo ln -s chromedriver /usr/bin/chromedriver
  - export DISPLAY=:1
  - sh -e /etc/init.d/xvfb start
  - curl "http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar" > selenium.jar
  - java -jar selenium.jar > /dev/null &
  - sleep 5
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - $HOME/islandora/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/drupal_selenium
  - drush -y -u 1 en selenium
script:
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh sites/all/modules/drupal_selenium
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer selenium
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/drupal_selenium
  # - drush --uri=http://localhost:8081 test-run "Drupal Selenium Integration"
